### ISSUE TITLE
Data must be 1-dimensional

### ISSUE THREAD

**Issue by shahlaebrahimi** [chasedehan/BoostARoota#9] opened 2017-12-07 06:39 UTC
I would appreciate if you could let me know how to deal with this error:
```
X = np.array(pd.read_csv('tot_X_1.csv',header=None).values)
y = np.array(pd.read_csv('tot_Y_1.csv',header=None).values.ravel())

# Split data set to train and test data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,stratify=y, test_size=0.3, random_state=42)

X_train=pd.get_dummies(X_train)


br = BoostARoota(metric='f1')

#Fit the model for the subset of variables
br.fit(X_train,y_train)

#Can look at the important variables - will return a pandas series
br.keep_vars_

#Then modify dataframe to only include the important variables
br.transform(X_train)
```
Error:
```
  File "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/Bankrupt_2/Bankrupt/data/chase.py", line 15, in <module>
    X_train=pd.get_dummies(X_train)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\pandas\core\reshape\reshape.py", line 1215, in get_dummies
    sparse=sparse, drop_first=drop_first)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\pandas\core\reshape\reshape.py", line 1222, in _get_dummies_1d
    codes, levels = _factorize_from_iterable(Series(data))
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\pandas\core\series.py", line 264, in __init__
    raise_cast_failure=True)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\pandas\core\series.py", line 3234, in _sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional
```
Best regards,

**Comment by shahlaebrahimi** [comment] 2017-12-07 07:35
Sorry I could fix it but now this error occurs:
```
Round:  1  iteration:  1
Round:  1  iteration:  2
Round:  1  iteration:  3
Round:  1  iteration:  4
Round:  1  iteration:  5
Round:  1  iteration:  6
Round:  1  iteration:  7
Round:  1  iteration:  8
Round:  1  iteration:  9
Round:  1  iteration:  10
Round:  2  iteration:  1
Round:  2  iteration:  2
Round:  2  iteration:  3
Round:  2  iteration:  4
Round:  2  iteration:  5
Round:  2  iteration:  6
Round:  2  iteration:  7
Round:  2  iteration:  8
Round:  2  iteration:  9
Round:  2  iteration:  10
Traceback (most recent call last):
  File "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/Bankrupt_2/Bankrupt/data/chase.py", line 25, in <module>
    br.fit(X_train,y_train)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\boostaroota\boostaroota.py", line 46, in fit
    silent=self.silent)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\boostaroota\boostaroota.py", line 163, in _BoostARoota
    silent=silent)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\boostaroota\boostaroota.py", line 134, in _reduce_vars
    if (len(real_vars['feature']) / len(x.columns)) > (1-delta):
ZeroDivisionError: division by zero
```

**Comment by chasedehan** [comment] 2017-12-07 15:16
Hmm, the "division by zero" error looks like it is thrown here: len(real_vars['feature']) / len(x.columns)

This tells me that x no longer has any columns remaining after the first round and that the algorithm is a bit too aggressive on removing variables.  I would suggest setting the parameters to only allowing a single round. i.e.
br = BoostARoota(metric='f1', max_rounds=1)

Hope this helps!

**Comment by shahlaebrahimi** [comment] 2017-12-07 15:19
Thanks. Sorry isn't it possible to use f measure as evaluation metric?

**Comment by chasedehan** [comment] 2017-12-07 16:37
any eval_metric recognized by xgboost should work (for binary or regression tasks - only mlogloss for multiclass).  In the code you got working above, did you use the F1 metric in it?  If so, what I pasted above should work with the max rounds.

The default parameters in the BoostARoota work pretty well, but don't generalize across every dataset.  Thats why, I think, you need to change the max rounds.

**Comment by chasedehan** [comment] 2017-12-08 16:33
I'm assuming your issue is solved - I'm going to close it.  Reach out to me directly if you have other questions.

**Closed by chasedehan** 2017-12-08 16:33 UTC
